### ISSUE TITLE
lockfile check is broken

### ISSUE THREAD

**Issue by MonadeDigitalStudio** [railsbump/app#78]
Hi there,
I've tried to check my Gemfile.lock using [this link](https://railsbump.org/lockfiles/new), but it fails silently.
(The button gets clicked, but no output is returned.

Browser console:
```
turbo.es2017-esm.js:2406 Error: Form responses must redirect to another location
    at B.requestSucceededWithResponse (turbo.es2017-esm.js:784:27)
    at H.receive (turbo.es2017-esm.js:546:27)
    at H.perform (turbo.es2017-esm.js:521:31)
formSubmissionErrored @ turbo.es2017-esm.js:2406
Show 1 more frame
Show less
new:1 The resource https://railsbump.org/assets/es-module-shims.min-295257ea6e233f6a8d82987e4107c1b3f9ed62ea.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
turbo.es2017-esm.js:2406 Error: Form responses must redirect to another location
    at B.requestSucceededWithResponse (turbo.es2017-esm.js:784:27)
    at H.receive (turbo.es2017-esm.js:546:27)
    at H.perform (turbo.es2017-esm.js:521:31)
formSubmissionErrored @ turbo.es2017-esm.js:2406
requestSucceededWithResponse @ turbo.es2017-esm.js:785
receive @ turbo.es2017-esm.js:546
perform @ turbo.es2017-esm.js:521
await in perform (async)
start @ turbo.es2017-esm.js:743
submitForm @ turbo.es2017-esm.js:2346
formSubmitted @ turbo.es2017-esm.js:3076
V.submitBubbled @ turbo.es2017-esm.js:951
Show 8 more frames
Show less
new:1 The resource https://railsbump.org/assets/application-80add165a4fc71ae22a50329406200974de78195.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
new:1 The resource https://railsbump.org/assets/es-module-shims.min-295257ea6e233f6a8d82987e4107c1b3f9ed62ea.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
new:1 The resource https://kit.fontawesome.com/0d43dadb44.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

Debugging the network, it looks like a database error:
<img width="332" alt="Screenshot 2024-01-04 at 11 41 12" src="https://github.com/railsbump/app/assets/57046749/d3d1dd32-1037-4f3c-8525-00c315445ea5">

**Comment by manuelmeurer** [comment]
Thanks for the report, @MonadeDigitalStudio! I'll try to fix it asap.

**Comment by orbulant** [comment]
Same here... i'm using it and i see the exact same problem in the Preview.

Hopefully it's fixed soon!

**Comment by manuelmeurer** [comment]
Fixed
