### ISSUE TITLE
check_with_bundler_locally fails for certain gems (likely a platform compatibility issue)

### ISSUE THREAD

**Issue by etagwerker** [railsbump/app#87]
# Expected

I'd expect `check_with_bundler_locally` to work (or to not attempt to bundle locally for a gem that is not compatible with my platform -- e.g. Mac OS X)

# Current

Right now it is raising an exception. More here: 

```
adapter = 50.4, jdbc-postgres >= 9.4, < 43, kwargs: {}, caller: /app/services/compats/check_unchecked.rb:30)
14:54:45 worker.1 | 2024-09-24T18:54:45.247Z pid=58526 tid=vu6 class=Compats::CheckUnchecked jid=6be171d82473f7e69d64a76a ERROR: Compats::Check::Error: Unexpected stderr: /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/resolver.rb:336:in `raise_not_found!': Could not find gem 'activerecord-jdbc-adapter (= 50.4)' with platform 'arm64-darwin-23' in rubygems repository https://rubygems.org/ or installed locally. (Bundler::GemNotFound)
14:54:45 worker.1 |
14:54:45 worker.1 | The source contains the following gems matching 'activerecord-jdbc-adapter (= 50.4)':
14:54:45 worker.1 | * activerecord-jdbc-adapter-50.4-java
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/resolver.rb:414:in `block in prepare_dependencies'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/resolver.rb:392:in `each'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/resolver.rb:392:in `map'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/resolver.rb:392:in `prepare_dependencies'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/resolver.rb:63:in `setup_solver'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/resolver.rb:28:in `start'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/definition.rb:626:in `start_resolution'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/definition.rb:305:in `resolve'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/definition.rb:179:in `resolve_remotely!'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/installer.rb:258:in `resolve_if_needed'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/installer.rb:82:in `block in run'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/process_lock.rb:12:in `block in lock'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/process_lock.rb:9:in `open'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/process_lock.rb:9:in `lock'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/installer.rb:71:in `run'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/installer.rb:23:in `install'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/inline.rb:58:in `block (3 levels) in gemfile'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/settings.rb:158:in `temporary'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/inline.rb:57:in `block (2 levels) in gemfile'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/settings.rb:158:in `temporary'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/inline.rb:51:in `block in gemfile'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler.rb:429:in `block in with_unbundled_env'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler.rb:684:in `with_env'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler.rb:429:in `with_unbundled_env'
14:54:45 worker.1 | from /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.13/lib/bundler/inline.rb:42:in `gemfile'
14:54:45 worker.1 | from /Users/etagwerker/Projects/railsbump/app/tmp/compats/724905:5:in `<main>'
14:54:45 worker.1 |   /Users/etagwerker/Projects/railsbump/app/app/services/compats/check.rb:158:in `check_with_bundler_locally'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service.rb:140:in `call'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service.rb:140:in `block in call_all_private_methods_without_args'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service.rb:139:in `each'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service.rb:139:in `call_all_private_methods_without_args'
14:54:45 worker.1 |   /Users/etagwerker/Projects/railsbump/app/app/services/compats/check.rb:31:in `call'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service/uniqueness_checker.rb:60:in `call'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service/exception_wrapper.rb:7:in `call'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service/call_logger.rb:10:in `call'
14:54:45 worker.1 |   /Users/etagwerker/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/bundler/gems/baseline-60a5488d0682/lib/baseline/service.rb:30:in `call'
14:54:45 worker.1 |   /Users/etagwerker/Projects/railsbump/app/app/services/compats/check_unchecked.rb:30:in `block (2 levels) in do_check'
```

**Comment by etagwerker** [comment]
This has been replaced with https://github.com/railsbump/app/blob/main/app/services/compats/checks/bundler_github_check.rb plus this GitHub action: https://github.com/railsbump/checker/blob/main/lib/rails_bump/checker/bundle_locally_check.rb
